---

- name: Configure sysctl and enable kernel mod paso 1
  shell: modprobe overlay
  become: yes

- name: Configure sysctl and enable kernel mod paso 2
  shell: |
          modprobe br_netfilter
          tee /etc/sysctl.d/k8s.conf<<EOF
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
          EOF
  become: yes

- name: Configure sysctl and enable kernel mod paso 3
  shell: sysctl --system
  become: yes

- name: Se desactiva AllowZoneDrifting
  lineinfile:
    dest: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting='
    line: "AllowZoneDrifting=no"
    state: present
  become: yes

- name: Se activa transparent masquerading para comunicación de los PODs
  firewalld:
    masquerade: yes
    state: enabled
    permanent: true
    zone: public
  become: yes

- name: Se reinicia el servicio firewall para aplicar cambios
  systemd:
    name: firewalld
    state: restarted
    enabled: yes
    masked: no
  become: yes

- name: Permitir que kubernetes maneje correctamente el tráfico con el cortafuegos
  copy:
    dest: "/etc/sysctl.d/k8s.conf"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  become: yes

- name: Se aplican todos los cambios realizados
  shell: sysctl --system
  become: yes

- name: Se desactiva el swap
  shell: swapoff -a
  become: yes

- name: Se elimina la línea del fichero /etc/fstab que monta en el arranque el swap
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'
  become: yes

- name: Se agrega repositorio libcontainers:stable.repo
  shell: dnf config-manager --add-repo=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
  args:
    creates: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
    warn: false
  become: yes

- name: Se agrega repositorio libcontainers:stable:cri-o:1.23:1.23.1.repo
  shell: dnf config-manager --add-repo=https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
  args:
    creates: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
    warn: false
  become: yes

- name: Se configura los modulos del kernel necesarios para CRI-O
  copy:
    dest: "/etc/modules-load.d/crio.conf"
    content: |
      overlay
      br_netfilter
  become: yes

- name: Se instala CRI-O.
  dnf:
    name: "{{ crio_packages }}"
    state: present
  become: yes

- name: Se activa el servicio CRI-O
  systemd:
    name: crio
    state: started
    enabled: yes
    masked: no
  become: yes

- name: Se configura el repositorio de Kubernetes
  yum_repository:
    name: kubernetes
    description: Repositorio oficial de Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl
  become: yes

- name: Se instala Kubernetes
  dnf:
    name: "{{ kubernetes_packages }}"
    state: present
    disable_excludes: kubernetes
  become: yes

- name: Se habilita e inicia el servicio de Kubernetes
  systemd:
    name: kubelet
    state: started
    enabled: yes
    masked: no
  become: yes